name: GodWar
author: alvin0319
main: alvin0319\GodWar\GodWar
version: 1.0.1
api: 3.0.0

mcpe-protocol: 431

extensions:
  Core: '>=7.4'

permissions:
  godwar.command:
    description: GodWar command permission
    default: op