<?php
declare(strict_types=1);
namespace alvin0319\GodWar\entity;

use pocketmine\entity\projectile\Projectile;
use pocketmine\event\entity\EntityExplodeEvent;
use pocketmine\level\Explosion;
use pocketmine\level\particle\HugeExplodeParticle;

class Fireball extends Projectile{

	protected $aliveTicks = 80;

	public function onUpdate(int $currentTick) : bool{
		$hasUpdate = parent::onUpdate($currentTick); // TODO: Change the autogenerated stub
		if(--$this->aliveTicks > 0 or $this->isCollided){
			$ev = new EntityExplodeEvent($this, $this, [], 0.0);
			$ev->call();

			$explode = new Explosion($this, 5);
			$explode->explodeA();

			$this->getLevel()->addParticle(new HugeExplodeParticle($this));
		}
		return $hasUpdate;
	}
}